using Looma.Application.Extraction;
using Looma.Application.UseCases;
using Looma.Core.Entities;
using Xunit;

namespace Looma.Application.Tests;

/// <summary>
/// Covers all four <see cref="DocumentExportFormat"/> values. The Pdf case
/// specifically round-trips the generated bytes through
/// <see cref="DocumentTextExtractor"/> (the same PdfPig-backed reader the
/// app already trusts for document-attach extraction) rather than just
/// checking for a non-empty byte array — real proof
/// <see cref="DocumentGeneration.PdfDocumentWriter"/> produces a PDF a real
/// reader can open and recover text from, not just something that starts
/// with the right magic bytes.
/// </summary>
public sealed class DocumentExportUseCaseTests : IDisposable
{
    private readonly string _tempPdfPath = Path.Combine(Path.GetTempPath(), $"looma-test-{Guid.NewGuid():N}.pdf");
    private readonly DocumentExportUseCase _useCase = new();

    [Fact]
    public async Task ExportAsync_Pdf_ProducesReadableDocumentWithTitleAndBody()
    {
        var bytes = await _useCase.ExportAsync(
            "Gene Tunney quote",
            "The quote about persistence is attributed to Gene Tunney.",
            DocumentExportFormat.Pdf);

        // %PDF is the format's own magic-number header — a cheap first check
        // before the real round-trip below.
        Assert.Equal("%PDF"u8.ToArray(), bytes[..4]);

        await File.WriteAllBytesAsync(_tempPdfPath, bytes);
        var extractedText = await DocumentTextExtractor.ExtractAsync(_tempPdfPath);

        Assert.Contains("Gene Tunney quote", extractedText);
        Assert.Contains("persistence is attributed to Gene Tunney", extractedText);
    }

    [Fact]
    public async Task ExportAsync_Pdf_LongContentPaginatesReadably()
    {
        // Long enough to force PdfDocumentWriter past one page — real proof
        // its EnsureRoom pagination produces a still-valid, still-readable
        // multi-page PDF, not just a single short page.
        var longContent = string.Join("\n\n", Enumerable.Range(1, 80)
            .Select(i => $"Paragraph {i}: this line exists only to take up vertical space on the page."));

        var bytes = await _useCase.ExportAsync("Long answer", longContent, DocumentExportFormat.Pdf);

        await File.WriteAllBytesAsync(_tempPdfPath, bytes);
        var extractedText = await DocumentTextExtractor.ExtractAsync(_tempPdfPath);

        Assert.Contains("Paragraph 1:", extractedText);
        Assert.Contains("Paragraph 80:", extractedText);
    }

    [Fact]
    public async Task ExportAsync_Word_ProducesNonEmptyDocxBytes()
    {
        var bytes = await _useCase.ExportAsync("Title", "Body text.", DocumentExportFormat.Word);

        // .docx is a zip container — "PK" signature is enough to confirm
        // DocxDocumentWriter actually ran rather than throwing.
        Assert.Equal("PK"u8.ToArray(), bytes[..2]);
    }

    [Fact]
    public async Task ExportAsync_Markdown_IncludesTitleAsHeading()
    {
        var bytes = await _useCase.ExportAsync("My Title", "Body text.", DocumentExportFormat.Markdown);
        var text = System.Text.Encoding.UTF8.GetString(bytes);

        Assert.Equal("# My Title\n\nBody text.", text);
    }

    [Fact]
    public async Task ExportAsync_PlainText_IncludesUnderlinedTitle()
    {
        var bytes = await _useCase.ExportAsync("Hi", "Body text.", DocumentExportFormat.PlainText);
        var text = System.Text.Encoding.UTF8.GetString(bytes);

        Assert.Equal("Hi\n==\n\nBody text.", text);
    }

    public void Dispose()
    {
        if (File.Exists(_tempPdfPath))
        {
            File.Delete(_tempPdfPath);
        }
    }
}
