using Looma.Core.Entities;

namespace Looma.Application.UseCases;

/// <summary>
/// Packages a chat answer's title + text into a real file's bytes — Word
/// (.docx), Markdown (.md), or plain text (.txt). Pure local formatting,
/// no LLM/vector-store/network dependency at all (the content it packages
/// was already generated by <see cref="IChatUseCase"/>/
/// <see cref="IChatCompletionUseCase"/> beforehand) — which is why this is
/// registered identically in both Standalone and McpClient mode with no
/// "Remote" adapter or MCP tool of its own; there's nothing to send over
/// the wire.
///
/// Deliberately returns bytes rather than writing to disk itself — where
/// (and whether) to save is a UI/OS concern (a native "Save As" dialog),
/// not this use case's job.
/// </summary>
public interface IDocumentExportUseCase
{
    Task<byte[]> ExportAsync(string title, string content, DocumentExportFormat format, CancellationToken cancellationToken = default);
}
